name: Manifest and Kubernetes Object Validation
on: 
  workflow_dispatch:
    inputs:
       yamllint-output:
          description: 'Define output style for yamlint'
          required: true
          type: string
       confirm:
          description: 'OK?'
          required: true
          type: boolean
jobs:
  validate:
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: List files in the repository
        run: ls
      
      - name: yamlint validation
        run: yamllint --format ${{ github.event.inputs.yamllint-output }} .

      - name: kubelinter validation
        run: kube-linter lint .

      - name: kubeval validation
        run: kubeval .