name: Manifest and Kubernetes Object Validation
on: 
  workflow_dispatch:
    inputs:
       confirm:
          description: 'OK?'
          required: true
          type: boolean
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
     
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint . 