name: Manifest and Kubernetes Object Validation
on:
  workflow_dispatch:
    inputs:
      yamllint-output:
         description: 'Define output style for yamlint'
         required: true
         type: string
      confirm:
         description: 'OK?'
         required: true
         type: boolean
jobs:
  validate:
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Verify current directory
        run: pwd
      
      - name: List all files
        run: ls
      
      - name: Get Files Changed
        id: getfile
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u)"

      - name: Print files
        run: echo ${{ steps.getfile.outputs.files }}

      - name: yamlint validation
        run: yamllint --format ${{ github.event.inputs.yamllint-output }} .
        continue-on-error: true

      - name: kubelinter validation
        run: kube-linter lint .
        continue-on-error: true

      - name: kubeval validation
        run: kubeval ./*/*/*/*/*
        continue-on-error: true
