name: Manifest and Kubernetes Object Validation
on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
jobs: 
  validate:
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      #  with:
      #    fetch-depth: 0

      #- name: Get changed files
      #  id: getdiff
      #  run: echo "::set-output name=diff::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} "*.yaml" "*.yml" | sed ':a;N;$!ba;s/\n/ /g')"
      
      #- name: list files
      #  id: getdiff
      #  run: |
      #    URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
      #    FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
      #    echo $FILES
      
      - name: get files changed
        uses: jitterbit/get-changed-files@v1
        id: files
      
      - run: |
           for changed_file in ${{ steps.files.outputs.all }}; do
              echo "Do something with this ${changed_file}."
           done

      #- name: yamllint validation
      #  run: yamllint --format colored ${{ steps.getdiff.outputs.diff }}
      #  continue-on-error: true

      #- name: kubeval validation
      #  run: kubeval ${{ steps.getdiff.outputs.diff }}
      #  continue-on-error: true