name: Manifest and Kubernetes Object Validation
on:
  [push]
jobs:
  get-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get file changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: Extra step
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}

  validate:
    needs: get-repo
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    steps:
      - name: yamlint validation
        run: yamllint --format ${{ github.event.inputs.yamllint-output }} .
        continue-on-error: true

      - name: kubelinter validation
        run: kube-linter lint .
        continue-on-error: true

      - name: kubeval validation
        run: kubeval ./*/*/*
        continue-on-error: true
